### ISSUE TITLE
Issues when using light groups

### ISSUE THREAD

**Issue by Aephir** [thomasloven/lovelace-folding-group-entity-row#1]
Hi,

Thanks for another great add-on. I think there is an issue, and after a bit of testing, **_I think_** it has to do with using lights that are "[light groups](https://www.home-assistant.io/components/light.group/)".

As an example, I have in light.yaml
```
- platform: group
  name: Kitchen Spots
  entities:
    - light.kitchen_spot_1
    - light.kitchen_spot_2
    - light.kitchen_spot_3
    - light.kitchen_spot_4
    - light.kitchen_spot_5
    - light.kitchen_spot_6

- platform: group
  name: Kitchen Cabinet Lights
  entities:
    - light.kitchen_cabinet_light_1
    - light.kitchen_cabinet_light_2
```
In group.yaml:
```
  kitchen_lights:
    name: Kitchen Lights
    entities:
      - light.kitchen_spots
      - light.kitchen_cabinet_lights
  conservatory_lights:
    name: Conservatory Lights
    entities:
      - light.conservatory_couch
      - light.conservatory_reading
```
And in ui-lovelace.yaml:
```
          - entity: group.conservatory_lights
            type: custom:folding-group-entity-row
            config:
              type: custom:slider-entity-row
            group_config:
              secondary_info: last-changed
          - entity: group.kitchen_lights
            type: custom:folding-group-entity-row
            config:
              type: custom:slider-entity-row
            group_config:
              secondary_info: last-changed
```
The one where I'm using light groups gives an error, other work just fine.

<img width="364" alt="screen shot 2018-09-29 at 16 03 24" src="https://user-images.githubusercontent.com/20152788/46246634-436c9100-c401-11e8-9682-b4de1dce253c.png">
