### ISSUE TITLE
Card toggle does not toggle folding-group

### ISSUE THREAD

**Issue by Aephir** [thomasloven/lovelace-folding-group-entity-row#3]
When you have a mixed card with both folding groups and other entities, the card toggle does not affect the folding-group.

E.g.:
<img width="369" alt="screen shot 2018-10-01 at 08 33 57" src="https://user-images.githubusercontent.com/20152788/46273191-c8b48a80-c554-11e8-87ab-fec7f7f04fcf.png">

Using any of the toggles for the folding-groups, they of course toggle the entire group. But the entire card can not be toggled.

Cheers

**Comment by thomasloven** [comment]
This is the default behavior of an entity card and, unfortunately, nothing I can do anything about.

In this example, the header toggle will not turn the group on or off:
```
- type: entities
  show_header_toggle: true
  entities:
    - group.my_group
    - light.my_light
```
